#!/bin/bash

local proto,iface,interface,port,baudrate,source_address,max_master,frames,model

model=$(cat /etc/fw_model)

proto=$(uci get dct.bacnet_client.proto)
if [ $proto == "0" ]; then
	echo "BACnet/IP"
	iface=$(uci get dct.bacnet_client.ifname)
	prot=$(uci get dct.bacnet_client.port)
	exprot BACNET_IP_PORT=$port
	export BACNET_IFACE=$iface
	
	/usr/sbin/bacdiscover_ip --print-seconds 2
else
	echo "BACnet/MSTP"
	interface=$(uci get dct.bacnet_client.interface)
	if [ $model == "EG324" ]; then
		if [ $interface == "COM1" ]; then
			iface="/dev/ttyAMA0"
		else
			iface="/dev/ttyAMA1"
		fi
	elif [ $model == "EG324L" ]; then
		if [ $interface == "COM1" ]; then
			iface="/dev/ttyS1"
		else
			iface="/dev/ttyS2"
		fi
	else
		iface="/dev/ttyACM0"
	fi
	baudrate=$(uci get dct.bacnet_client.baudrate)
	source_address=$(uci get dct.bacnet_client.mac)
	max_master=$(uci get dct.bacnet_client.max_master)
	frames=$(uci get dct.bacnet_client.frames)
	export BACNET_IFACE=$iface
	echo $BACNET_IFACE
	export BACNET_MSTP_BAUD=$baudrate
	export BACNET_MSTP_MAC=$source_address
	export BACNET_MAX_MASTER=$max_master
	export BACNET_MAX_INFO_FRAMES=$frames
	
	/usr/sbin/bacdiscover_mstp --print-seconds 2
fi
